import { describe, it, expect } from "vitest";
import { verifyTimedToken } from "../../src/auth/itsdangerous.js";

const SECRET = "test-secret";
// Generated by Python: URLSafeTimedSerializer("test-secret").dumps("admin")
const FRESH_TOKEN = "ImFkbWluIg.ai3Ldw.xJxBF063GPqe6k4Hsbfag6klGL4";
const TEN_YEARS = 10 * 365 * 24 * 3600;

describe("verifyTimedToken", () => {
  it("accepts a valid token and returns the payload", () => {
    const res = verifyTimedToken(FRESH_TOKEN, SECRET, TEN_YEARS);
    expect(res.valid).toBe(true);
    expect(res.payload).toBe("admin");
  });

  it("rejects a tampered signature", () => {
    const bad = FRESH_TOKEN.slice(0, -2) + (FRESH_TOKEN.endsWith("a") ? "bb" : "aa");
    expect(verifyTimedToken(bad, SECRET, TEN_YEARS).valid).toBe(false);
  });

  it("rejects when signed with a different secret", () => {
    expect(verifyTimedToken(FRESH_TOKEN, "wrong-secret", TEN_YEARS).valid).toBe(false);
  });

  it("rejects an expired token (maxAge 0)", () => {
    expect(verifyTimedToken(FRESH_TOKEN, SECRET, 0).valid).toBe(false);
  });

  it("rejects malformed tokens", () => {
    expect(verifyTimedToken("not-a-token", SECRET, 1000).valid).toBe(false);
  });
});
